Merged in update-docs-on-release (pull request #662)
Add script to update docs in docs repo on release

* Build docs locally without mount

* Install chr in docs generator container

* Run chr install before trying to generate the docs

* Remove caches section

* Add some printouts to display what the pipeline is doing

* Use another API key

* Generate a new bitbucket access token

* Update name of API token config value

* Update curl command

* Fix formatting of JSON body

* Generate client docs to the same directory as the docs repo script do

* Use propper version in created PR

* Use package version of ft lib instead of docs repo

* Use chr version 0.20.1

* Use apt-get to install chr

* Don't use sudo in pipeline

* Revert change that installed chr from apt-get

* Fail pipeline if we don't get a success response when opening PR

* Close source branch on merge

* Test failing the pipeline

* Pipeline should pass when we successfully create a PR

* Only run update api docs step when merging to master

* Move scripts into scripts folder

* Merge branch 'development' into update-docs-on-release

* Merged development into update-docs-on-release


Approved-by: Francesco Santanché
Approved-by: Joso Markovic

diff --git a/bitbucket-pipelines.yml b/bitbucket-pipelines.yml
--- a/bitbucket-pipelines.yml
+++ b/bitbucket-pipelines.yml
@@ -9,7 +9,7 @@ unit-integration-tests: &unit-integration-tests-anchor
   caches:
     - node
   script:
-    - ./install-chr-and-pmc.sh
+    - ./scripts/install-chr-and-pmc.sh
     - chr install
     - chr build
     - chr test --use-db --test-report --test-report-dir=test-reports/rell || (curl --no-progress-meter -X POST https://chromadev.zulipchat.com/api/v1/messages -u ${BUILD_BOT_EMAIL_ADDRESS}:${BUILD_BOT_API_KEY} --data-urlencode type=stream --data-urlencode 'to="Protocols - FT4 builds"' --data-urlencode 'topic=Build failed' --data-urlencode "content=Rell tests failed on [Bitbucket](https://bitbucket.org/chromawallet/ft3-lib/pipelines/results/${BITBUCKET_BUILD_NUMBER})." ; exit 1)
@@ -43,7 +43,7 @@ e2e-tests: &e2e-tests-anchor
       - ln -s /opt/amazon-corretto-21.0.2.13.1-linux-x64/bin/java /usr/bin/java
       - java -version
 
-      - ./install-chr-and-pmc.sh
+      - ./scripts/install-chr-and-pmc.sh
 
       - export DISPLAY=:0.0
       - Xvfb :0 -screen 0 1024x768x24 -listen tcp -ac &
@@ -66,9 +66,71 @@ multichain-tests: &multichain-tests-anchor
   services:
     - docker
   script:
-    - ./install-chr-and-pmc.sh
+    - ./scripts/install-chr-and-pmc.sh
     - npm ci
     - bash scripts/multichain-jesttest.sh
+
+update-docs: &update-docs-anchor
+  max-time: 15
+  name: Update docs
+  services:
+    - docker
+  script: 
+    - |
+      export DOCKER_BUILDKIT=1
+      GIT_EMAIL=`git config user.email`
+      GIT_NAME=`git config user.name`
+      git clone https://x-token-auth:$DOCS_REPO_API_TOKEN@bitbucket.org/chromawallet/chromia-docs.git docs-repo
+      
+      ./scripts/install-chr-and-pmc.sh
+      npm ci
+      npx typedoc --out docs-repo/static/pages/ft4-ts-client/client
+      chr install
+      chr build
+      chr generate docs-site --target docs-repo/static/pages/ft4-rell
+
+      VERSION=`npm pkg get version | tr -d '"'`
+      cd docs-repo
+
+      # Check if there are changes 
+      if [ `git status --porcelain | wc -l` -gt 0 ]; then
+        # Commit and push the changes
+        BRANCH=ft4-version-$VERSION
+
+        git config user.email $GIT_EMAIL
+        git config user.name $GIT_NAME
+
+        git checkout -b $BRANCH
+        git add .
+        git commit -m "Update ft4 api docs to version $VERSION"
+        
+        echo "Pushing the changes to remote"
+        git push origin $BRANCH
+        echo "Successfully pushed changes to remote"
+
+        echo "Opening a PR in docs repo"
+        HTTP_STATUS=$(curl -v \
+            --header 'Authorization: Bearer '"$DOCS_REPO_API_TOKEN" \
+            --header 'Accept: application/json' \
+            --header 'Content-Type: application/json' \
+            --data '{
+              "title": "BUILD_USER: Update ft4 api docs to version '"$VERSION"'",
+              "source": {"branch": {"name": "'"$BRANCH"'"}},
+              "destination": {"branch": {"name": "master"}},
+              "close_source_branch": true
+            }' \
+            --write-out '%{http_code}' \
+            --output response.txt \
+            "https://api.bitbucket.org/2.0/repositories/chromawallet/chromia-docs/pullrequests")
+        
+        if [ "$HTTP_STATUS" -ge 299 ]; then
+          echo "Failed to open PR with status <"$HTTP_STATUS"> and message:"
+          cat response.txt
+          exit 1
+        fi
+      else
+        echo "No changes to commit."
+      fi
 
 pipelines:
   pull-requests:
@@ -84,7 +146,7 @@ pipelines:
       - step:
           name: deploy:latest
           script:
-            - ./install-chr-and-pmc.sh
+            - ./scripts/install-chr-and-pmc.sh
             - chr install
             - mkdir .chromia
             - printf $DEPLOYMENT_KEYS > .chromia/config
@@ -97,12 +159,15 @@ pipelines:
         - step:
             <<: *e2e-tests-anchor
             trigger: manual
+    master:
+      - step: *update-docs-anchor
+          
   custom:
     deploy-to-stable:
       - step:
           name: deploy:stable
           script:
-            - ./install-chr-and-pmc.sh
+            - ./scripts/install-chr-and-pmc.sh
             - chr install
             - mkdir .chromia
             - printf $DEPLOYMENT_KEYS > .chromia/config
@@ -112,7 +177,7 @@ pipelines:
       - step:
           name: deploy:latest
           script:
-            - ./install-chr-and-pmc.sh
+            - ./scripts/install-chr-and-pmc.sh
             - chr install
             - mkdir .chromia
             - printf $DEPLOYMENT_KEYS > .chromia/config
